name: Build Debug APK

on:
  create:
    tags:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: 'platform-31'

      - name: Build Debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
          
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/app-debug.apk
