name: Build Debug APK

on:
  create:
    tags:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: '30'
          sdk-distribution: 'cmdline-tools'

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Build Debug APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug
          
      - name: Upload APK
        id: upload-apk
        uses: actions/upload-artifact@v2
        with:
          name: Debug APK
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN2 }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Attach APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN2 }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{ steps.upload-apk.outputs.artifact_paths }}
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive
