name: Build Signed APK

on:
  create:
    tags:
      - "*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: '30'
          sdk-distribution: 'cmdline-tools'

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Assemble Release
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        id: sign_release
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        id: upload-apk
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN2 }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN2 }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/app-release.apk
          asset_name: ${{ github.event.repository.name }}.apk
          asset_content_type: application/zip
